name: Test

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: debian:buster

    steps:
    - name: install dependencies
      run: |
        apt-get update
        apt-get --no-install-recommends -y install admesh git imagemagick jekyll make openscad python3 python3-yaml xauth xvfb python3-pip python3-setuptools
        python3 -mpip install cookiecutter
    - name: git setup
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: checkout
      uses: actions/checkout@v2
    - name: cut a cookie
      run: cookiecutter --no-input .
    - name: build within the cookie
      run: xvfb-run make V=2 -O -j$(nproc) -C mystl jekyll
